const { spawnSync } = require("node:child_process");
const { mkdtempSync, writeFileSync } = require("node:fs");
const { tmpdir } = require("node:os");
const { resolve } = require("node:path");
const ts = require("typescript");
const root = resolve(__dirname, "../../..");
const output = mkdtempSync(resolve(tmpdir(), "qualitzer-branding-validation-"));
const tests = ["tests/company-branding.test.ts", "src/branding/tests/stability.test.ts", "src/branding/tests/context.test.ts"];
const result = spawnSync(process.execPath, ["node_modules/tsx/dist/cli.mjs", "--tsconfig", "server/tsconfig.json", "--test", "--test-reporter=spec", ...tests], { cwd: root, encoding: "utf8" });
const config = ts.readConfigFile(resolve(root, "tsconfig.json"), ts.sys.readFile);
const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, root);
const targets = [...tests, "App.tsx", "src/branding/companyBrandingContext.ts", "src/branding/companyBranding.ts", "src/branding/contracts.ts", "src/branding/CompanyBrandingController.ts", "src/branding/useCompanyBranding.ts", "modules/company-branding/index.ts"].map((file) => resolve(root, file));
const program = ts.createProgram(targets, { ...parsed.options, noEmit: true, types: [...new Set([...(parsed.options.types ?? []), "node"])] });
const diagnostics = ts.getPreEmitDiagnostics(program).filter((item) => !item.file || targets.includes(resolve(item.file.fileName))).map((item) => ({ file: item.file?.fileName, code: item.code, message: ts.flattenDiagnosticMessageText(item.messageText, "\n") }));
const report = { observedAt: new Date().toISOString(), exit: result.status, error: result.error?.message, stdout: result.stdout, stderr: result.stderr, diagnostics };
writeFileSync(resolve(output, "report.json"), JSON.stringify(report, null, 2));
console.log(output);
console.log(result.stdout, result.stderr, JSON.stringify(diagnostics));
process.exitCode = result.status === 0 && diagnostics.length === 0 ? 0 : 1;