import { StyleSheet } from "react-native";
import { palette, radius, typography } from "../../ui/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  screen: { flex: 1 },
  header: { width: "100%", maxWidth: 900, alignSelf: "center", paddingHorizontal: 12, paddingVertical: 8, flexDirection: "row", alignItems: "center", gap: 8 },
  headerText: { flex: 1, minWidth: 0, gap: 2 },
  code: { ...typography.label, color: palette.text },
  content: { width: "100%", maxWidth: 900, alignSelf: "center", padding: 16, paddingBottom: 36, gap: 20 },
  stack: { gap: 16 },
  tight: { gap: 8 },
  row: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 10 },
  between: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", alignItems: "center", gap: 12 },
  grow: { flex: 1, minWidth: 0 },
  column: { flexGrow: 1, flexBasis: 240, minWidth: 0, gap: 16 },
  columns: { flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start", gap: 16 },
  title: { ...typography.title, color: palette.text },
  heading: { ...typography.heading, color: palette.text },
  label: { ...typography.label, color: palette.text },
  caption: { ...typography.caption, color: palette.textSecondary },
  overline: { ...typography.overline, color: palette.primary },
  muted: { color: palette.textMuted },
  hero: { borderRadius: radius.xl, padding: 24, gap: 18, overflow: "hidden" },
  heroTitle: { ...typography.title, color: palette.white },
  heroOverline: { ...typography.overline, color: palette.onDark },
  heroText: { ...typography.body, color: palette.onDark },
  timerBox: { borderRadius: radius.lg, padding: 18, gap: 6, borderColor: palette.darkBorder, borderWidth: 1, backgroundColor: palette.darkSurface },
  timer: { fontSize: 36, lineHeight: 44, fontWeight: "700", color: palette.white, fontVariant: ["tabular-nums"], letterSpacing: 1 },
  heroMetrics: { flexDirection: "row", flexWrap: "wrap", gap: 24 },
  metric: { gap: 4, flexGrow: 1 },
  metricValue: { ...typography.label, color: palette.white },
  tabs: { flexDirection: "row", flexWrap: "wrap", gap: 6, padding: 6, borderRadius: radius.lg, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border },
  tab: { flexGrow: 1, flexBasis: 140, minHeight: 48, borderRadius: radius.md, paddingHorizontal: 10, paddingVertical: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  activeTab: { backgroundColor: palette.primarySoft },
  tabText: { ...typography.label, color: palette.textSecondary },
  activeTabText: { color: palette.primary },
  notice: { borderRadius: radius.md, padding: 16, gap: 8, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.infoSoft },
  noticeError: { backgroundColor: palette.dangerSoft, borderColor: "#F0C9CB" },
  noticeWarning: { backgroundColor: palette.amberSoft, borderColor: "#EFDEBC" },
  noticeSuccess: { backgroundColor: palette.successSoft, borderColor: "#C5E5D1" },
  errorText: { ...typography.body, color: palette.danger },
  choice: { minHeight: 48, borderWidth: 1, borderColor: palette.border, borderRadius: radius.md, padding: 12, gap: 8, flexDirection: "row", alignItems: "center", backgroundColor: palette.surface },
  choiceSelected: { borderColor: palette.primary, backgroundColor: palette.primarySoft },
  choiceText: { ...typography.label, color: palette.text, flexShrink: 1 },
  disabled: { opacity: 0.55 },
  divider: { height: 1, backgroundColor: palette.border },
  item: { borderBottomWidth: 1, borderBottomColor: palette.border, paddingVertical: 12, gap: 8 },
  multiline: { minHeight: 124, textAlignVertical: "top" },
  progressTrack: { height: 8, borderRadius: radius.pill, backgroundColor: palette.track, overflow: "hidden" },
  progressFill: { height: "100%", backgroundColor: palette.primary, borderRadius: radius.pill },
  stepNumber: { width: 36, height: 36, borderRadius: 12, backgroundColor: palette.primarySoft, alignItems: "center", justifyContent: "center" },
  photos: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  photoCard: { flexBasis: 220, flexGrow: 1, maxWidth: 400, gap: 8, borderWidth: 1, borderColor: palette.border, borderRadius: radius.md, padding: 10 },
  photo: { width: "100%", height: 180, borderRadius: radius.sm, backgroundColor: palette.track },
  attachment: { gap: 10, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: palette.border },
  previewPress: { minHeight: 48, borderRadius: radius.md, overflow: "hidden" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(18,44,58,0.60)", justifyContent: "center", padding: 16 },
  modalCard: { width: "100%", maxWidth: 680, maxHeight: "100%", alignSelf: "center", borderRadius: radius.xl, backgroundColor: palette.surface, overflow: "hidden" },
  modalContent: { padding: 24, gap: 20 },
  viewer: { flex: 1, backgroundColor: palette.navy },
  viewerImage: { flex: 1, width: "100%" },
  viewerHeader: { padding: 16, gap: 12 },
  viewerTitle: { ...typography.label, color: palette.white },
});