import { StyleSheet } from "react-native";
import { palette, radius, typography } from "../../ui/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.background },
  screen: { flex: 1 },
  hidden: { display: "none" },
  detailNavigation: { flexDirection: "row", alignItems: "center", backgroundColor: palette.surface, borderBottomWidth: 1, borderBottomColor: palette.border, paddingHorizontal: 8, flexShrink: 0 },
  header: { width: "100%", maxWidth: 900, alignSelf: "center", paddingHorizontal: 6, paddingVertical: 4, flexDirection: "row", alignItems: "center", gap: 2 },
  headerCodes: { flex: 1, minWidth: 0 },
  headerCodeRow: { flexDirection: "row", alignItems: "center", gap: 5 },
  headerCode: { fontSize: 11, lineHeight: 17, fontWeight: "700", color: palette.primary, backgroundColor: palette.primarySoft, paddingHorizontal: 4, paddingVertical: 5, borderRadius: 4, flexShrink: 0 },
  headerStatus: { fontSize: 11, lineHeight: 17, fontWeight: "600", color: palette.textSecondary, flexShrink: 0 },
  executionFooter: { flexShrink: 0, width: "100%", backgroundColor: palette.surface, borderTopWidth: 1, borderTopColor: palette.border, paddingHorizontal: 12, paddingVertical: 10, gap: 5 },
  executionButtons: { width: "100%", maxWidth: 900, alignSelf: "center", flexDirection: "row", gap: 8 },
  executionButton: { flex: 1, minWidth: 0, paddingHorizontal: 8, paddingVertical: 10 },
  headerText: { flex: 1, minWidth: 0, gap: 2 },
  closedBanner: { paddingHorizontal: 16, paddingVertical: 8, gap: 8, flexDirection: "row", alignItems: "center", backgroundColor: palette.successSoft, borderBottomWidth: 1, borderBottomColor: palette.primary },
  checklistHeader: { width: "100%", maxWidth: 900, alignSelf: "center", paddingHorizontal: 8, paddingVertical: 2, flexDirection: "row", alignItems: "center", gap: 4 },
  checklistHeaderButton: { minHeight: 44, paddingHorizontal: 8, paddingVertical: 8 },
  code: { ...typography.label, color: palette.text },
  content: { width: "100%", maxWidth: 900, alignSelf: "center", padding: 16, paddingBottom: 36, gap: 20 },
  stack: { gap: 16 },
  workSections: { gap: 28 },
  detailSection: { borderTopWidth: 1, borderTopColor: palette.border, paddingTop: 20, gap: 12 },
  sectionHeading: { minHeight: 44, flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
  sectionTitle: { fontSize: 18, lineHeight: 24, fontWeight: "700", color: palette.text, flexGrow: 1, flexShrink: 1, minWidth: 0 },
  checklistLink: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 14, paddingHorizontal: 12, backgroundColor: palette.primarySoft, borderRadius: 6 },
  activityCard: { backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border, borderLeftWidth: 3, borderLeftColor: palette.primary, borderRadius: 8, padding: 14, gap: 12 },
  activityRecent: { borderColor: palette.primary },
  activityTitle: { fontSize: 17, lineHeight: 24, fontWeight: "700", color: palette.text, flex: 1 },
  activityIndex: { fontSize: 12, lineHeight: 18, fontWeight: "700", color: palette.textMuted },
  activityActions: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6, borderTopWidth: 1, borderTopColor: palette.border, paddingTop: 6 },
  tight: { gap: 8 },
  row: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 10 },
  between: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", alignItems: "center", gap: 12 },
  grow: { flex: 1, minWidth: 0 },
  column: { flexGrow: 1, flexBasis: 240, minWidth: 0, gap: 16 },
  columns: { flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start", gap: 16 },
  title: { ...typography.title, color: palette.text },
  heading: { ...typography.heading, color: palette.text },
  label: { ...typography.label, color: palette.text },
  caption: { ...typography.caption, color: palette.textSecondary },
  overline: { ...typography.overline, color: palette.primary },
  muted: { color: palette.textMuted },
  hero: { borderRadius: radius.md, padding: 14, gap: 8, overflow: "hidden" },
  heroTitle: { ...typography.heading, color: palette.white },
  heroOverline: { ...typography.overline, color: palette.onDark },
  heroText: { ...typography.body, color: palette.onDark },
  timerBox: { gap: 2 },
  timer: { fontSize: 24, lineHeight: 30, fontWeight: "700", color: palette.white, fontVariant: ["tabular-nums"], letterSpacing: 0 },
  heroMetrics: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  metric: { gap: 4, flexGrow: 1 },
  metricValue: { ...typography.label, color: palette.white },
  tabs: { flexDirection: "row", gap: 4, paddingVertical: 5, backgroundColor: palette.surface },
  tab: { minHeight: 44, borderRadius: 6, paddingHorizontal: 10, paddingVertical: 8, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
  activeTab: { backgroundColor: palette.primarySoft },
  tabText: { ...typography.label, color: palette.textSecondary },
  activeTabText: { color: palette.primary },
  notice: { borderRadius: radius.md, padding: 16, gap: 8, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.infoSoft },
  noticeError: { backgroundColor: palette.dangerSoft, borderColor: "#F0C9CB" },
  noticeWarning: { backgroundColor: palette.amberSoft, borderColor: "#EFDEBC" },
  noticeSuccess: { backgroundColor: palette.successSoft, borderColor: "#C5E5D1" },
  errorText: { ...typography.body, color: palette.danger },
  choice: { minHeight: 48, borderWidth: 1, borderColor: palette.border, borderRadius: radius.md, padding: 12, gap: 8, flexDirection: "row", alignItems: "center", backgroundColor: palette.surface },
  choiceSelected: { borderColor: palette.primary, backgroundColor: palette.primarySoft },
  choiceText: { ...typography.label, color: palette.text, flexShrink: 1 },
  disabled: { opacity: 0.55 },
  divider: { height: 1, backgroundColor: palette.border },
  item: { borderBottomWidth: 1, borderBottomColor: palette.border, paddingVertical: 12, gap: 8 },
  multiline: { minHeight: 124, textAlignVertical: "top" },
  progressTrack: { height: 8, borderRadius: radius.pill, backgroundColor: palette.track, overflow: "hidden" },
  progressFill: { height: "100%", backgroundColor: palette.primary, borderRadius: radius.pill },
  stepNumber: { width: 36, height: 36, borderRadius: 12, backgroundColor: palette.primarySoft, alignItems: "center", justifyContent: "center" },
  photos: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  photoCard: { flexBasis: 220, flexGrow: 1, maxWidth: 400, gap: 8, borderWidth: 1, borderColor: palette.border, borderRadius: radius.md, padding: 10 },
  photo: { width: "100%", height: 180, borderRadius: radius.sm, backgroundColor: palette.track },
  attachment: { gap: 10, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: palette.border },
  previewPress: { minHeight: 48, borderRadius: radius.md, overflow: "hidden" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(18,44,58,0.60)", justifyContent: "center", padding: 16 },
  modalCard: { width: "100%", maxWidth: 680, maxHeight: "100%", alignSelf: "center", borderRadius: radius.xl, backgroundColor: palette.surface, overflow: "hidden" },
  modalContent: { padding: 24, gap: 20 },
  viewer: { flex: 1, backgroundColor: palette.navy },
  viewerImage: { flex: 1, width: "100%" },
  viewerHeader: { padding: 16, gap: 12 },
  viewerTitle: { ...typography.label, color: palette.white },
});