import { StyleSheet } from "react-native";
import { palette, radius, typography } from "../../../ui/theme";

export const checklistStyles = StyleSheet.create({
  catalog: { gap: 12 },
  catalogCard: { padding: 16, gap: 12 },
  cardHeading: { flexDirection: "row", alignItems: "center", gap: 12 },
  cardIcon: { width: 42, height: 42, borderRadius: radius.md, backgroundColor: palette.primarySoft, justifyContent: "center", alignItems: "center" },
  name: { ...typography.label, color: palette.text, fontSize: 16, lineHeight: 23 },
  code: { ...typography.caption, color: palette.textSecondary },
  pressed: { opacity: 0.75 },
  panel: { padding: 16, gap: 16 },
  navigation: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  navigationButton: { flexGrow: 1, flexBasis: 120 },
  stepRow: { minHeight: 64, padding: 12, borderWidth: 1, borderColor: palette.border, borderRadius: radius.md, flexDirection: "row", alignItems: "center", gap: 10 },
  selectedRow: { borderColor: palette.primary, backgroundColor: palette.primarySoft },
  snapshot: { backgroundColor: palette.background, borderRadius: radius.md, borderWidth: 1, borderColor: palette.border, padding: 12, gap: 6 },
  comment: { minHeight: 96, textAlignVertical: "top" },
  screen: { flex: 1, minHeight: 0, width: "100%", maxWidth: 900, alignSelf: "center", backgroundColor: palette.surface },
  scroll: { flex: 1, minHeight: 0 },
  scrollContent: { padding: 12, paddingBottom: 20, gap: 12 },
  toolbar: { paddingHorizontal: 8, paddingVertical: 4, gap: 4, borderBottomWidth: 1, borderColor: palette.border },
  toolbarRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  toolbarTitle: { flex: 1, minWidth: 0, gap: 2 },
  title: { ...typography.label, color: palette.text },
  progress: { ...typography.caption, color: palette.textSecondary },
  progressTrack: { height: 3, borderRadius: radius.pill, backgroundColor: palette.track, overflow: "hidden" },
  question: { gap: 10 },
  questionHeading: { ...typography.heading, color: palette.text, fontSize: 20, lineHeight: 27 },
  stepMeta: { flexDirection: "row", flexWrap: "wrap", gap: 6, alignItems: "center" },
  actions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  compactButton: { minHeight: 44, paddingHorizontal: 10, paddingVertical: 8 },
  dock: { flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12, paddingVertical: 6, borderTopWidth: 1, borderColor: palette.border, backgroundColor: palette.surface },
  dockSave: { flex: 1, minWidth: 0, minHeight: 44, paddingHorizontal: 8, paddingVertical: 8 },
  dockHint: { flex: 1, ...typography.caption, color: palette.textSecondary, textAlign: "center" },
});